name: CI
on:
  - pull_request
jobs:
  cypress-run:
    name: Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@25a956c84d5dd820d28caab9f86b8d183aeeff3d # v2
      - name: Write sample patrons.json file
        run: echo "[]" > utils/data/patrons.json
      - name: Cypress run
        uses: cypress-io/github-action@9eab5368cd2520a946489cd3f937583ff5a30443 # v2
        with:
          start: npm run dev
